apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels: 
        app: conversao-temperatura
    spec:
      containers:
        - name: web
          image: tsecco/conversao-temperatura:latest
          ports:
            - containerPort: 8080